# Generated by Django 4.2.11 on 2026-03-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instructor'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Morning Men, Women, Evening Men', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gym Shift',
                'verbose_name_plural': 'Gym Shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Assigned instructor (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.instructor'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Member's direct contact number", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Assigned gym timing slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='finance.gymshift'),
        ),
    ]
