# Generated by Django 5.2.12 on 2026-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_email1',
            field=models.EmailField(default='support@fitnessfreaks.com', help_text='Application contact email 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_email2',
            field=models.EmailField(default='support@fitnessfreaks.com', help_text='Application contact email 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(default='Fitness Freak', help_text='Application name', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='short_name',
            field=models.CharField(default='FF', help_text='Your application short name', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='terms_url',
            field=models.URLField(default='https://fitnessfreaks.com/terms-of-use/', help_text='Terms and Conditions page link', max_length=255),
        ),
    ]
